image: ubuntu:latest

stages:
  - deploy

pages:
  stage: deploy
  script:
    - echo "Downloading ZIP file..."
    - wget -O igem-dna-sonify-pages.zip https://gitlab.igem.org/zivmax/igem-dna-sonify/-/archive/pages/igem-dna-sonify-pages.zip    - echo "Unzipping..."
    - unzip igem-dna-sonify-pages.zip
    - rm igem-dna-sonify-pages.zip
    - mv igem-dna-sonify-pages/* public/
  artifacts:
    paths:
      - public
