image: curlimages/curl:latest

stages:
  - deploy

pages:
  stage: deploy
  script:
    - echo "Downloading ZIP file..."
    - curl -L -o public.zip https://gitlab.igem.org/zivmax/igem-dna-sonify/-/archive/pages/igem-dna-sonify-pages.zip    
    - unzip public.zip
    - rm public.zip
  artifacts:
    paths:
      - public
