image: curlimages/curl:latest

stages:
  - deploy

pages:
  stage: deploy
  script:
    - echo "Downloading ZIP file..."
    - curl -L -o igem-dna-sonify-pages.zip https://gitlab.igem.org/zivmax/igem-dna-sonify/-/archive/pages/igem-dna-sonify-pages.zip    
    - unzip igem-dna-sonify-pages.zip
    - rm igem-dna-sonify-pages.zip
    - mkdir public/
    - mv igem-dna-sonify-pages/* public/
  artifacts:
    paths:
      - public
