image: node:latest

before_script:
  - corepack enable
  - corepack prepare pnpm@latest-9 --activate
  - pnpm config set store-dir .pnpm-store

pages:
  stage: deploy
  script:
    - pnpm install -r --frozen-lockfile --prod # install dependencies
    - ./node_modules/.bin/gatsby build
  artifacts:
    paths:
      - public
  only:
    - main
